- name: Installing the elasticsearch cluster
  hosts: tag_Name_node*
  become: yes
  become_user: root
  roles:
  - { role: elasticsearch, es_instance_name: "node1", es_config: {cluster.name: "production",  node.data: true, node.master: true }}
  - { role: kibana }
  - { role: metricbeat }
  vars:
    es_version: 7.9.2
    es_repo_name: 7.x
    es_heap_size: 256m
